os:
  - linux
  - osx
  - windows

# https://travis-ci.community/t/timeout-after-build-finished-and-succeeded/1336
env:
  - YARN_GPG=no

language: rust
rust: nightly

# Unable to use cache on windows, so we remove it
cache:
  cargo: true
  yarn: true
  directories:
    - node_modules

install:
  - cargo build --release --manifest-path gtmserv/Cargo.toml

script:
  - cargo test --release --manifest-path gtmserv/Cargo.toml

before_deploy:
  - if [ "$TRAVIS_OS_NAME" = "linux" ] || [ "$TRAVIS_OS_NAME" = "osx" ]; then nvm install node && npm install --global yarn ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install nodejs && choco install yarn; fi
  # Force update of path env var on windows
  # Choco updates only for powershell
  - export PATH=$PATH:"/c/Program Files/nodejs"
  - node --version || true
  - export PATH=$PATH:"/c/Program Files (x86)/Yarn/bin"
  - yarn --version || true
  - yarn install --check-files
  - yarn build
  - yarn test
  - yarn dist

deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file:
      # - dist/gtm-dash_0.1.0_amd64.snap
      - dist/gtm-dash-0.1.0.AppImage
      - dist/gtm-dash-0.1.0.dmg
      - "dist/gtm-dash Setup 0.1.0.exe"
    prerelease: true
    overwrite: true
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/demo
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux