os:
  - linux
  - osx
  - windows

# https://travis-ci.community/t/timeout-after-build-finished-and-succeeded/1336
env:
  - YARN_GPG=no

language: rust
rust: nightly

cache:
  # yarn: true
  cargo: true
  directories:
    - node_modules

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ] || [ "$TRAVIS_OS_NAME" = "osx" ]; then nvm install node && npm install --global yarn ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install nodejs && choco install yarn; fi
  # Force update of path env var on windows
  # Choco updates only for powershell
  - export PATH=$PATH:"/c/Program Files/nodejs"
  - node --version || true
  - export PATH=$PATH:"/c/Program Files (x86)/Yarn/bin"
  - yarn --version || true

install:
  - yarn install

script:
  - cargo build --release --manifest-path gtmserv/Cargo.toml
  - cargo test --manifest-path gtmserv/Cargo.toml
  - yarn build
  - yarn test
  - yarn dist

deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file:
      - dist/gtm-dash_0.0.1_amd64.snap
      - dist/gtm-dash-0.0.1.AppImage
      - dist/gtm-dash-0.0.1.dmg
      - "dist/gtm-dash Setup 0.0.1.exe"
    draft: true
    on:
      branch: develop
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/demo
    on:
      branch: master