os:
  - linux
  - osx
  - windows

# https://travis-ci.community/t/timeout-after-build-finished-and-succeeded/1336
env:
  - YARN_GPG=no

# language: node_js
language: rust
rust: nightly
# node_js: v13.12.0

cache:
  yarn: true
  cargo: true
  directories:
    - node_modules

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then npm install --global yarn ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then npm install --global yarn ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install yarn ; fi

install:
  - cargo build --release --manifest-path gtmserv/Cargo.toml

script:
  - "cargo test --manifest-path gtmserv/Cargo.toml"

before_deploy:
  - "npm run build"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/demo
  on:
    branch: master