os:
  - linux
  - osx
  - windows

language: node_js
node_js: v13.12.0

cache:
  yarn: true
  directories:
    - node_modules

before_deploy:
  - "npm run build"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/demo
  on:
    branch: master