os:
  - linux
  - osx
  - windows

# https://travis-ci.community/t/timeout-after-build-finished-and-succeeded/1336
env:
  - YARN_GPG=no

# language: node_js
language: rust
rust: nightly
# node_js: v13.12.0

cache:
  yarn: true
  cargo: true
  directories:
    - node_modules

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ] || [ "$TRAVIS_OS_NAME" = "osx" ]; then nvm install node && npm install --global yarn ; fi
  # - if [ "$TRAVIS_OS_NAME" = "osx" ]; then npm install --global yarn ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install nodejs && choco install yarn; fi
  # - if [ "$TRAVIS_OS_NAME" = "windows" ]; then  ; fi

install:
  - yarn install

script:
  - cargo build --release --manifest-path gtmserv/Cargo.toml
  - cargo test --manifest-path gtmserv/Cargo.toml
  - yarn build
  - yarn test
  - yarn dist

# before_deploy:
#   - "npm run build"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/demo
  on:
    branch: master